Improve docker pushing workflow on CI

diff --git a/docker_push b/docker_push
--- a/docker_push
+++ b/docker_push
@@ -1,3 +1,34 @@
 #!/bin/bash
 echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
-docker push ahugues/porygon-backend
+
+package_version=v$(npm version | grep "porygon-backend" | awk -F ':' '{ print $2; }' | tr -d ",' ")
+echo "Pushing docker images for version $package_version"
+
+# push latest master image
+echo "Pushing master image"
+docker tag ahugues/porygon-backend ahugues/porygon-backend:master
+docker push ahugues/porygon-backend:master
+
+# # only tag latest and versionned image on tagged commit
+if [ -z "$TRAVIS_TAG" ]
+then
+    echo "Not a tagged build, exiting..."
+    exit 0
+fi
+
+
+if [ "$package_version" != "$TRAVIS_TAG" ]
+then
+    >&2 echo "ERROR: tag [$TRAVIS_TAG] and package version [$package_version] don't match, exiting..."
+    exit 1
+fi
+
+# push image associated with current version
+echo "Pushing image for tag $TRAVIS_TAG"
+docker tag ahugues/porygon-backend ahugues/porygon-backend:$TRAVIS_TAG
+docker push ahugues/porygon-backend:$TRAVIS_TAG
+
+# push image associated with latest tag
+echo "Pushing latest image"
+docker tag ahugues/porygon-backend ahugues/porygon-backend:latest
+docker push ahugues/porygon-backend:latest
